language: java
sudo: required
jdk:
  - openjdk7

cache:
  directories:
  - $HOME/.m2

install:
  - export PATH=$PATH:$HOME/.local/bin

services:
 - docker

before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

script:
 - mvn -B clean install

after_success:
 - docker --version
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
 - mv iris/target/iris.war docker/
 - cd $TRAVIS_BUILD_DIR
 - chmod ugo+x DeployScripts/code_docker_deploy.sh
 - chmod ugo+x DeployScripts/app_docker_deploy.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: ./DeployScripts/code_docker_deploy.sh
    on:
      tags: true
  - provider: releases
    api_key: $GIT_API_KEY
    file: 
    - docker/iris.war
    - iris-shared/target/iris-shared.jar
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: ./DeployScripts/code_docker_deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./DeployScripts/code_docker_deploy.sh
    on:
      branch: dev
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
    skip_cleanup: true
    on:
      tags: true
